<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHjxeyjz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHjxeyjz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHjxeyjz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHjxeyjz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHjxeyjz\appProdProjectContainer([
    'container.build_hash' => 'Hjxeyjz',
    'container.build_id' => '9d5a6941',
    'container.build_time' => 1640055903,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHjxeyjz');
